name: splitzy
description: A minimal expense splitting app built with Flutter.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  provider: ^6.1.2
  
  # Firebase (Free tier)
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^11.6.0
  
  # Authentication
  google_sign_in: ^5.4.4
  path_provider: ^2.1.4
  file_picker: ^10.2.1
  permission_handler: ^12.0.1
  permission_handler: ^12.0.1
  pdf: ^3.11.1
  open_filex: ^4.5.0
  flutter_local_notifications: ^19.4.0
  local_auth: ^2.3.0
  share_plus: ^11.0.0
  connectivity_plus: ^6.1.0
  google_fonts: ^6.2.1
  
  # Local Storage
  shared_preferences: ^2.3.2
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  
  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.1
  logger: ^2.0.2+1
  
  # Image Handling
  image_picker: ^1.1.2
  image: ^4.1.7
  
  # Notifications
  flutter_local_notifications: ^19.4.0
  
  # Charts
  fl_chart: ^0.66.2
  
  # Reactive Programming
  rxdart: ^0.28.0
  
  # Contacts
  flutter_contacts: ^1.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  json_annotation: ^4.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/splash_light.png
    - assets/upi_icon.png
    - assets/sample_receipt.jpg

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700